-- Baseline PostgreSQL migration for Supabase. It is intentionally idempotent and does not delete data.
DO $$ BEGIN CREATE TYPE "user_role" AS ENUM ('user', 'admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "staff_role" AS ENUM ('owner', 'catalog_manager', 'project_manager', 'viewer'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "catalog_node_type" AS ENUM ('category', 'option'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "project_status" AS ENUM ('draft', 'submitted', 'under_review', 'locked', 'in_progress', 'completed', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "device_platform" AS ENUM ('ios', 'android'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "attachment_status" AS ENUM ('pending', 'uploaded', 'failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  "name" text, "email" varchar(320), "loginMethod" varchar(64),
  "role" "user_role" NOT NULL DEFAULT 'user',
  "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), "lastSignedIn" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "customer_profiles" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" integer NOT NULL,
  "fullName" varchar(180), "phone" varchar(32), "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "customer_profiles_user_id_unique" ON "customer_profiles" ("userId");
CREATE TABLE IF NOT EXISTS "staff_members" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" integer, "email" varchar(320) NOT NULL,
  "displayName" varchar(180), "role" "staff_role" NOT NULL DEFAULT 'viewer', "isActive" boolean NOT NULL DEFAULT true,
  "createdByUserId" integer, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "staff_members_email_unique" ON "staff_members" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "staff_members_user_id_unique" ON "staff_members" ("userId");
CREATE INDEX IF NOT EXISTS "staff_members_role_active_idx" ON "staff_members" ("role", "isActive");
CREATE TABLE IF NOT EXISTS "company_settings" (
  "id" integer PRIMARY KEY, "legalName" varchar(180) NOT NULL, "arabicName" varchar(180) NOT NULL,
  "supportEmail" varchar(320) NOT NULL, "supportPhone" varchar(32), "address" text, "website" varchar(300), "logoUrl" text,
  "publicTagline" varchar(300) NOT NULL, "publicHeroTitle" varchar(300) NOT NULL, "publicHeroBody" text, "reportFooter" varchar(500) NOT NULL,
  "ownerUserId" integer, "backupOwnerUserId" integer, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "admin_activity_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "actorUserId" integer NOT NULL, "action" varchar(100) NOT NULL,
  "entityType" varchar(100) NOT NULL, "entityId" integer, "summary" varchar(500) NOT NULL, "metadataJson" text, "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "admin_activity_logs_created_idx" ON "admin_activity_logs" ("createdAt");
CREATE INDEX IF NOT EXISTS "admin_activity_logs_actor_idx" ON "admin_activity_logs" ("actorUserId");
CREATE TABLE IF NOT EXISTS "services" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "slug" varchar(120) NOT NULL, "defaultSortOrder" integer NOT NULL DEFAULT 0,
  "name" varchar(180) NOT NULL, "description" text, "imageUrl" text, "sortOrder" integer NOT NULL DEFAULT 0, "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "services_slug_unique" ON "services" ("slug");
CREATE INDEX IF NOT EXISTS "services_active_order_idx" ON "services" ("isActive", "sortOrder");
CREATE TABLE IF NOT EXISTS "catalog_nodes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "serviceId" integer NOT NULL, "parentId" integer,
  "nodeType" "catalog_node_type" NOT NULL DEFAULT 'category', "name" varchar(180) NOT NULL, "description" text, "imageUrl" text,
  "sortOrder" integer NOT NULL DEFAULT 0, "isActive" boolean NOT NULL DEFAULT true, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "catalog_nodes_service_parent_order_idx" ON "catalog_nodes" ("serviceId", "parentId", "sortOrder");
CREATE INDEX IF NOT EXISTS "catalog_nodes_active_idx" ON "catalog_nodes" ("isActive");
CREATE TABLE IF NOT EXISTS "products" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "serviceId" integer NOT NULL, "catalogNodeId" integer NOT NULL,
  "name" varchar(220) NOT NULL, "description" text, "productCode" varchar(120), "mainImageUrl" text,
  "customerPrice" numeric(12,2), "internalCostPrice" numeric(12,2), "isAvailable" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true,
  "sortOrder" integer NOT NULL DEFAULT 0, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "products_catalog_active_order_idx" ON "products" ("catalogNodeId", "isActive", "sortOrder");
CREATE INDEX IF NOT EXISTS "products_service_idx" ON "products" ("serviceId");
CREATE UNIQUE INDEX IF NOT EXISTS "products_code_unique" ON "products" ("productCode");
CREATE TABLE IF NOT EXISTS "product_images" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "productId" integer NOT NULL, "imageUrl" text NOT NULL,
  "altText" varchar(240), "sortOrder" integer NOT NULL DEFAULT 0, "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "product_images_product_order_idx" ON "product_images" ("productId", "sortOrder");
CREATE TABLE IF NOT EXISTS "projects" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" integer NOT NULL, "title" varchar(180) NOT NULL,
  "propertyType" varchar(80), "city" varchar(100), "address" text, "areaSqm" numeric(10,2), "notes" text,
  "status" "project_status" NOT NULL DEFAULT 'draft', "progressPercent" integer NOT NULL DEFAULT 0, "assignedStaffId" integer,
  "submittedAt" timestamptz, "lockedAt" timestamptz, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "projects_user_status_updated_idx" ON "projects" ("userId", "status", "updatedAt");
CREATE INDEX IF NOT EXISTS "projects_assigned_staff_idx" ON "projects" ("assignedStaffId");
CREATE TABLE IF NOT EXISTS "project_updates" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "projectId" integer NOT NULL, "status" "project_status" NOT NULL,
  "progressPercent" integer NOT NULL DEFAULT 0, "title" varchar(180) NOT NULL, "note" text, "createdByUserId" integer, "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "project_updates_project_created_idx" ON "project_updates" ("projectId", "createdAt");
CREATE TABLE IF NOT EXISTS "project_update_images" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "projectUpdateId" integer NOT NULL, "storageKey" text NOT NULL, "imageUrl" text NOT NULL,
  "fileName" varchar(255) NOT NULL, "mimeType" varchar(120), "fileSizeBytes" integer, "caption" varchar(500), "sortOrder" integer NOT NULL DEFAULT 0, "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "project_update_images_update_order_idx" ON "project_update_images" ("projectUpdateId", "sortOrder");
CREATE TABLE IF NOT EXISTS "user_device_tokens" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "userId" integer NOT NULL, "expoPushToken" varchar(255) NOT NULL,
  "platform" "device_platform" NOT NULL, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "user_device_tokens_token_unique" ON "user_device_tokens" ("expoPushToken");
CREATE INDEX IF NOT EXISTS "user_device_tokens_user_idx" ON "user_device_tokens" ("userId");
CREATE TABLE IF NOT EXISTS "project_services" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "projectId" integer NOT NULL, "serviceId" integer NOT NULL,
  "notes" text, "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "project_services_project_service_unique" ON "project_services" ("projectId", "serviceId");
CREATE INDEX IF NOT EXISTS "project_services_project_idx" ON "project_services" ("projectId");
CREATE TABLE IF NOT EXISTS "project_selections" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "projectId" integer NOT NULL, "projectServiceId" integer NOT NULL,
  "productId" integer, "catalogNodeId" integer, "quantity" integer NOT NULL DEFAULT 1, "notes" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "project_selections_project_service_idx" ON "project_selections" ("projectId", "projectServiceId");
CREATE TABLE IF NOT EXISTS "project_attachments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "projectId" integer NOT NULL, "userId" integer NOT NULL,
  "storageKey" text NOT NULL, "fileName" varchar(255) NOT NULL, "mimeType" varchar(120), "fileSizeBytes" integer,
  "uploadStatus" "attachment_status" NOT NULL DEFAULT 'pending', "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "project_attachments_project_idx" ON "project_attachments" ("projectId");
CREATE INDEX IF NOT EXISTS "project_attachments_user_idx" ON "project_attachments" ("userId");
