-- إشعارات دائمة داخل التطبيق مرتبطة بمالك المشروع فقط.
DO $$ BEGIN
  CREATE TYPE "user_notification_kind" AS ENUM ('project_update', 'pricing_ready', 'project_completed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "user_notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "projectId" integer NOT NULL,
  "projectUpdateId" integer,
  "kind" "user_notification_kind" NOT NULL DEFAULT 'project_update',
  "title" varchar(180) NOT NULL,
  "body" text,
  "readAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "user_notifications_user_read_created_idx"
  ON "user_notifications" ("userId", "readAt", "createdAt");
CREATE INDEX IF NOT EXISTS "user_notifications_project_idx"
  ON "user_notifications" ("projectId");
